version: "3.8"
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - app-network
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/academic_db
      - REDIS_CLOUD_URL=redis://redis:6379
      - JWT_SECRET=erthjksaoiuyfasghxjashsaaksad
    volumes:
      - ./backend:/app
    networks:
      - app-network
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=academic_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network
  redis:
    image: redis:6
    ports:
      - "6379:6379"
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru
    networks:
      - app-network
volumes:
  postgres_data:
networks:
  app-network:
    driver: bridge
